namespace eval ::msgcat_exp1 {
::msgcat::mcset zh_tw "ArrayCode" "行列查碼程式"
::msgcat::mcset zh_tw "File" "檔案"
::msgcat::mcset zh_tw "Help" "幫助"
::msgcat::mcset zh_tw "Quit" "離開"
::msgcat::mcset zh_tw "Exit" "離開"
::msgcat::mcset zh_tw "About" "關於"
::msgcat::mcset zh_tw "code" "編碼"
::msgcat::mcset zh_tw "(No data found)" "（搜尋不到此字資料）"
::msgcat::mcset zh_tw "Really quit?" "確定要離開？"
::msgcat::mcset zh_tw "It is a simple tool to query Array30 Input Method code." "這是一個用來查詢行列三十輸入法編碼的簡單工具。"
}
