; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=行列查碼程式
AppVerName=行列查碼程式 v3.2
VersionInfoVersion=3.2.0.0
DefaultDirName={pf}\ArrayCode
DefaultGroupName=行列查碼程式
OutputBaseFilename=setup
Compression=lzma
SolidCompression=yes

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Projects\arraycode\arraycode.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projects\arraycode\array30_5401.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projects\arraycode\array30_nt4.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projects\arraycode\array30_siso.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projects\arraycode\array30_u20.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projects\arraycode\array30_u31.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projects\arraycode\array30_w9598.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projects\arraycode\mingwm10.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projects\arraycode\libgcc_s_dw2-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projects\arraycode\libstdc++-6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Projects\arraycode\arraycode.mo"; DestDir: "{app}/zh_TW/"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\行列查碼程式"; Filename: "{app}\arraycode.exe"
Name: "{group}\{cm:UninstallProgram,行列查碼程式}"; Filename: "{uninstallexe}"
Name: "{userdesktop}\行列查碼程式"; Filename: "{app}\arraycode.exe"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\行列查碼程式"; Filename: "{app}\arraycode.exe"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\arraycode.exe"; Description: "{cm:LaunchProgram,行列查碼程式}"; Flags: nowait postinstall skipifsilent

